#!/usr/bin/env bash
# This script transfers files from a client to a server
# It accepts arguments from the terminal to achieve this

if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# to disable strict host key checking
# this allows for file transfer without prompting for confirmation
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

scp -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
