#!/usr/bin/env bash
# this script automates ths installation of nginx

# installing nginx
apt-get -y update
apt-get -y install nginx

# set up nginx default landing page
echo "Hello world!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "/server_name _;/a \
	\\\n\terror_page 404 /404.html; \
	\n\n\tlocation /redirect_me { \
	\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
	\n\t}" /etc/nginx/sites-available/default

service nginx restart
